name: Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Get Surelog version
      id: get-surelog
      run: |
        echo "::set-output name=version::$(git rev-parse HEAD:third_party/tools/surelog)"

    - uses: actions/cache@v2
      id: surelog-cache
      if: matrix.os != 'ubuntu-latest'
      with:
        path: |
          siliconcompiler/tools/surelog/bin/surelog*
          siliconcompiler/tools/surelog/lib/surelog/sv/builtin.sv
        key: ${{ matrix.os }}-${{ steps.get-surelog.outputs.version }}

    - name: Setup env (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y graphviz winflexbison3
        vcpkg install zlib zlib:x64-windows
        .github/workflows/bin/install_klayout_win.bat

    - name: Setup env (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install graphviz
        brew install --cask klayout
        # https://github.com/ponty/PyVirtualDisplay/blob/master/.github/workflows/main.yml#L45
        brew install --cask xquartz
        echo "/opt/X11/bin" >> $GITHUB_PATH
        mkdir /tmp/.X11-unix
        sudo chmod 1777 /tmp/.X11-unix
        sudo chown root /tmp/.X11-unix

    - name: Build Surelog (Windows)
      if: matrix.os == 'windows-latest' && steps.surelog-cache.outputs.cache-hit != 'true'
      run: .github/workflows/bin/install_surelog_win.bat

    - name: Build Surelog (macOS)
      if: matrix.os == 'macos-latest' && steps.surelog-cache.outputs.cache-hit != 'true'
      run: .github/workflows/bin/install_surelog_macos.sh

    - uses: pypa/cibuildwheel@v2.1.1
      env:
        # Hack: LEF parser build is broken for currently bundled version of
        # OpenROAD, so check out old version.
        CIBW_BEFORE_ALL: >
          git -C {package} submodule update --init --recursive third_party/tools/openroad &&
          cd {package}/third_party/tools/openroad &&
          git checkout 3be623 &&
          git submodule update --init --recursive
        CIBW_BEFORE_ALL_LINUX: >
          export PREFIX={package}/siliconcompiler/tools/surelog &&
          {package}/.github/workflows/bin/setup_wheel_env_linux.sh
        CIBW_ENVIRONMENT: CI_BUILD_TYPE=${{ github.event_name }}
        CIBW_ENVIRONMENT_WINDOWS: SC_CMAKEARGS="-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake."
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_SKIP: "pp* *win32 *i686"
        MACOSX_DEPLOYMENT_TARGET: "10.15"
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_TEST_SKIP: "*_arm64"
        CIBW_TEST_EXTRAS: test
        CIBW_TEST_COMMAND: >
          pytest --import-mode=append {package}/tests/ -m "not eda" &&
          pytest --import-mode=append {package}/tests/tools/test_surelog.py &&
          pytest --import-mode=append {package}/tests/core/test_show.py

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && !contains(github.event.release.body, 'NOPUBLISH')

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_DEPLOY }}

  offline_package:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - run: |
          # Make and enter scratch directory
          mkdir -p /tmp/sc_package
          cd /tmp/sc_package

          # Make venv for installing wheels
          $PYTHON -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install siliconcompiler --find-links $GITHUB_WORKSPACE/dist/

          # Download all dependencies in current env into scdeps/
          mkdir scdeps
          pip freeze > scdeps/requirements.txt
          pip download -r scdeps/requirements.txt -d scdeps

          # Tar up scdeps/
          tar -czvf scdeps.tar.gz scdeps/

          # Clean up
          deactivate
          cd -
          mv /tmp/sc_package/scdeps.tar.gz scdeps-${{matrix.python-vesion}}.tar.gz
          rm -rf /tmp/sc_package

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          path: scdeps*.tar.gz
